services:
  mongo-boek:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_boek_data:/data/db

  mongo-lid:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_lid_data:/data/db

  mysql-bespreking:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_bespreking_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-recensie:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_recensie_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  lid-service:
    depends_on:
      - mongo-lid
    image: thijslintermans/lid-service
    ports:
      - 8080:8080
    links:
      - mongo-lid
    environment:
      MONGODB_PORT: 27018
      MONGODB_HOST: mongo-lid

  boek-service:
    depends_on:
      - mongo-boek
    image: thijslintermans/boek-service
    ports:
      - 8082:8082
    links:
      - mongo-boek
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-boek

  bespreking-service:
    depends_on:
      - mysql-bespreking
    image: thijslintermans/bespreking-service
    ports:
      - 8083:8083
    links:
      - mysql-bespreking
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-bespreking
      MYSQL_DB_PORT: 3307

  recensie-service:
    depends_on:
      - boek-service
      - lid-service
      - mysql-recensie
    image: thijslintermans/recensie-service
    ports:
      - 8081:8081
    links:
      - boek-service
      - lid-service
      - mysql-recensie
    environment:
      BOEK_SERVICE_BASEURL: boek-service:8082
      LID_SERVICE_BASEURL: lid-service:8080
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-recensie
      MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - boek-service
      - lid-service
      - recensie-service
    image: thijslintermans/api-gateway
    ports:
      - 8084:8084
    links:
      - boek-service
      - lid-service
      - recensie-service
    environment:
      BOEK_SERVICE_BASEURL: boek-service:8082
      LID_SERVICE_BASEURL: lid-service:8080


  volumes:
    mongodb_lid_data:
    mongodb_boek_data:
    mysql_bespreking_data:
    mysql_recensie_data: