server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10       # Number of requests per second
              burstCapacity: 20
      routes:
        - id: lid-service-get
          uri: http://${LID_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/lid
            - Method=GET
          filters:
            - SetPath=/api/lid/all
        - id: lid-service-post
          uri: http://${LID_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/lid
            - Method=POST
          filters:
            - SetPath=/api/lid
        - id: lid-service-put
          uri: http://${LID_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/lid/{id}
            - Method=PUT
          filters:
            - SetPath=/api/lid/{id}
        - id: lid-service-delete
          uri: http://${LID_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/lid/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/lid/{id}

        - id: boek-service-get
          uri: http://${BOEK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/boek
            - Method=GET
          filters:
            - SetPath=/api/boek/all
            - name: Cors
              args:
                allowedOrigins: "http://localhost:4200"
                allowedMethods: "GET, POST, PUT, DELETE"
                allowedHeaders: "Content-Type, Authorization"
        - id: boek-service-post
          uri: http://${BOEK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/boek
            - Method=POST
          filters:
            - SetPath=/api/boek
        - id: boek-service-put
          uri: http://${BOEK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/boek/{id}
            - Method=PUT
          filters:
            - SetPath=/api/boek/{id}
        - id: boek-service-delete
          uri: http://${BOEK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/boek/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/boek/{id}

        - id: bespreking-service-get
          uri: http://${BESPREKING_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/bespreking
            - Method=GET
          filters:
            - SetPath=/api/bespreking
            - name: Cors
              args:
                allowedOrigins: "http://localhost:4200"
                allowedMethods: "GET, POST, PUT, DELETE"
                allowedHeaders: "Content-Type, Authorization"
        - id: bespreking-service-post
          uri: http://${BESPREKING_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/bespreking
            - Method=POST
          filters:
            - SetPath=/api/bespreking
        - id: bespreking-service-put
          uri: http://${BESPREKING_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/bespreking/{id}
            - Method=PUT
          filters:
            - SetPath=/api/bespreking/{id}
        - id: bespreking-service-delete
          uri: http://${BESPREKING_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/besprekingen/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/bespreking/{id}

        - id: recensie-service-get
          uri: http://${RECENSIE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/recensies
            - Method=GET
          filters:
            - SetPath=/api/recensies
            - name: Cors
              args:
                allowedOrigins: "http://localhost:4200"
                allowedMethods: "GET, POST, PUT, DELETE"
                allowedHeaders: "Content-Type, Authorization"
        - id: recensie-service-get-by-lid
          uri: http://${RECENSIE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/recensies/{lidId}
            - Method=GET
          filters:
            - SetPath=/api/recensies/{lidId}
        - id: recensie-service-post
          uri: http://${RECENSIE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/recensies
            - Method=POST
          filters:
            - SetPath=/api/recensies
        - id: recensie-service-put
          uri: http://${RECENSIE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/recensies/{id}
            - Method=PUT
          filters:
            - SetPath=/api/recensies/{id}
        - id: recensie-service-delete
          uri: http://${RECENSIE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/recensies/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/recensies/{id}
